---
- name: Update infra configuration
  gather_facts: yes
  hosts: all
  
- name: Provision RKE2 controller
  gather_facts: yes
  hosts: mgmt
  become: true
  roles:
    - rke2-master # required. The name of the role to be executed.
- name: register token
  hosts: mgmt
  become: true
  tasks: 
    - name: capature token
    - name: register token for node connection
      register:
- name: Provision RKE2 agent
  gather_facts: yes
  serial: 1
  hosts: cluster
  become: true
  roles:
    - rke2-agent