---
- name: Ensure necessary packages are installed
  ansible.builtin.yum:
    name:
    - curl
    - sudo
    state: present
- name: Install RKE2 server
  ansible.builtin.shell: |
    curl -sfL https://get.rke2.io | sh -
  args:
    creates: /usr/local/bin/rke2
- name: Enable and start RKE2 server service
  ansible.builtin.systemd:
    name: rke2-server
    enabled: yes
    state: started
- name: restart RKE2 server service
  ansible.builtin.systemd:
    name: rke2-server
    state: restarted