---
- name: Install RKE2 agent
  ansible.builtin.shell: |
    curl -sfL https://get.rke2.io | INSTALL_RKE2_TYPE="agent" sh -
  args:
    creates: /usr/local/bin/rke2
- name: Create configuration directory
  ansible.builtin.file:
    path: /etc/rancher/rke2
    state: directory
